(() => {
  const form=document.getElementById('projectForm');if(!form)return;
  const list=document.getElementById('adminProjectList'),status=document.getElementById('adminStatus'),preview=document.getElementById('imagePreview'),fileInput=document.getElementById('image'),description=document.getElementById('description');
  let selectedFiles=[],existingImages=[],existingIds=[],editingId='';
  const esc=s=>window.BayuProjects.escapeHtml(s||'');
  function setStatus(t,type=''){status.textContent=t;status.className=`admin-status ${type}`;}
  function renderPreview(){let html=existingImages.map((src,i)=>`<div class="preview-item"><img src="${src}" alt="Foto tersimpan ${i+1}"><button type="button" class="preview-remove" data-delete-image="${existingIds[i]}">×</button>${i===0?'<span class="cover-badge">COVER</span>':''}</div>`).join('');html+=selectedFiles.map((f,i)=>`<div class="preview-item"><img src="${URL.createObjectURL(f)}" alt="Foto baru ${i+1}"><button type="button" class="preview-remove" data-remove-new="${i}">×</button>${existingImages.length===0&&i===0?'<span class="cover-badge">COVER</span>':''}</div>`).join('');preview.innerHTML=html||'<span>Belum ada foto.</span>';}
  async function load(){const ps=await window.BayuProjects.loadProjects(true);document.getElementById('adminCount').textContent=ps.length;list.innerHTML=ps.map(p=>{const imgs=window.BayuProjects.getImages(p);return `<article class="admin-project-item"><div class="admin-project-thumb">${imgs[0]?`<img src="${imgs[0]}" alt="">`:`<span>${esc(p.category)}</span>`}<b class="photo-count">${imgs.length} foto</b></div><div class="admin-project-info"><div class="admin-project-meta"><span>${esc(p.category)}</span><time>${new Date(p.createdAt).toLocaleDateString('id-ID')}</time></div><h3>${esc(p.title)}</h3><p>${esc(p.description)}</p><div class="admin-item-actions"><button data-edit="${p.id}">Edit</button><button data-delete="${p.id}" class="danger">Hapus</button><a href="project.html?id=${encodeURIComponent(p.id)}" target="_blank">Lihat Gallery</a></div></div></article>`}).join('')||'<p class="admin-empty">Belum ada project.</p>';}
  function reset(){form.reset();editingId='';existingImages=[];existingIds=[];selectedFiles=[];document.getElementById('projectId').value='';document.getElementById('formTitle').textContent='Tambah Project';document.getElementById('editingBadge').textContent='NEW';document.getElementById('saveBtn').textContent='Simpan Project';renderPreview();updateCount();setStatus('');}
  async function edit(id){const p=await window.BayuProjects.getProject(id);if(!p)return;editingId=id;document.getElementById('projectId').value=id;document.getElementById('title').value=p.title;document.getElementById('category').value=p.category;document.getElementById('description').value=p.description;document.getElementById('link').value=p.link||'';existingImages=[...p.images];existingIds=[...p.imageIds];selectedFiles=[];fileInput.value='';document.getElementById('formTitle').textContent='Edit Project';document.getElementById('editingBadge').textContent='EDIT';document.getElementById('saveBtn').textContent='Update Project';renderPreview();setStatus(`${existingImages.length} foto tersimpan. Tambahkan foto baru bila perlu.`,'success');scrollTo({top:0,behavior:'smooth'});}
  function updateCount(){document.getElementById('charCount').textContent=description.value.length;}description.addEventListener('input',updateCount);
  fileInput.addEventListener('change',()=>{selectedFiles=[...selectedFiles,...fileInput.files];fileInput.value='';renderPreview();});
  preview.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.removeNew!==undefined){selectedFiles.splice(Number(b.dataset.removeNew),1);renderPreview();}if(b.dataset.deleteImage){if(!confirm('Hapus foto ini dari gallery?'))return;try{const r=await fetch(`api/projects.php?action=delete-image&image_id=${b.dataset.deleteImage}`,{method:'DELETE'});const d=await r.json();if(!d.ok){setStatus(d.message,'error');return;}const idx=existingIds.indexOf(Number(b.dataset.deleteImage));if(idx>=0){existingIds.splice(idx,1);existingImages.splice(idx,1);}renderPreview();setStatus('Foto dihapus.','success');window.BayuProjects.loadProjects(true);}catch(err){setStatus('Gagal menghapus foto.','error');}}});
  form.addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData();fd.append('action',editingId?'update':'create');if(editingId)fd.append('id',editingId);fd.append('title',document.getElementById('title').value.trim());fd.append('category',document.getElementById('category').value);fd.append('description',description.value.trim());fd.append('link',document.getElementById('link').value.trim());const all=editingId?existingImages.length+selectedFiles.length:selectedFiles.length;if(!editingId&&!selectedFiles.length){setStatus('Tambahkan minimal 1 foto.','error');return;}if(all>30){setStatus('Maksimal 30 foto per project.','error');return;}selectedFiles.forEach(f=>fd.append('images[]',f));const btn=document.getElementById('saveBtn');btn.disabled=true;btn.textContent='Menyimpan...';try{const r=await fetch('api/projects.php',{method:'POST',body:fd});const d=await r.json();if(!d.ok){setStatus(d.message||'Gagal menyimpan.','error');return;}await window.BayuProjects.loadProjects(true);await load();reset();setStatus(editingId?'Project berhasil diupdate dan tersimpan online.':'Project berhasil ditambahkan dan tersimpan online.','success');}catch(err){setStatus('Server tidak dapat dihubungi.','error');}finally{btn.disabled=false;btn.textContent=editingId?'Update Project':'Simpan Project';}});
  list.addEventListener('click',async e=>{const ed=e.target.closest('[data-edit]'),del=e.target.closest('[data-delete]');if(ed)return edit(ed.dataset.edit);if(del){const id=del.dataset.delete,p=(await window.BayuProjects.loadProjects()).find(x=>String(x.id)===String(id));if(!confirm(`Hapus project "${p?.title||''}" beserta semua fotonya?`))return;const r=await fetch(`api/projects.php?action=delete-project&id=${id}`,{method:'DELETE'}),d=await r.json();if(d.ok){await window.BayuProjects.loadProjects(true);await load();reset();setStatus('Project dan semua fotonya berhasil dihapus.','success');}else setStatus(d.message||'Gagal menghapus.','error');}});
  document.getElementById('cancelEdit').addEventListener('click',reset);document.getElementById('resetData')?.addEventListener('click',()=>alert('Pada versi database online, reset massal dinonaktifkan agar project tidak terhapus tanpa sengaja. Gunakan Hapus pada project yang dipilih.'));load();updateCount();renderPreview();
})();
