(() => {
  const API = 'api/projects.php';
  let cache = [];
  const FALLBACK = [
    {id:'uiux-portfolio',title:'Portfolio UI/UX',category:'UI/UX Design',description:'Perancangan antarmuka portfolio dengan fokus pada hierarchy visual, typography, warna, dan pengalaman pengguna yang sederhana serta modern.',images:[],createdAt:'2026-08-20T10:00:00.000Z'},
    {id:'school-website',title:'School Website',category:'Website',description:'Website informasi sekolah dengan struktur halaman responsif, navigasi yang jelas, dan tampilan yang mudah digunakan di desktop maupun mobile.',images:[],createdAt:'2026-08-19T10:00:00.000Z'},
    {id:'event-poster',title:'Event Poster',category:'Graphic Design',description:'Desain poster kegiatan dengan komposisi visual yang kuat, warna kontras, dan informasi utama yang mudah dibaca.',images:[],createdAt:'2026-08-18T10:00:00.000Z'},
    {id:'social-media-design',title:'Social Media Design',category:'Graphic Design',description:'Konten visual media sosial untuk kebutuhan publikasi acara, branding, dan dokumentasi dengan gaya visual yang konsisten.',images:[],createdAt:'2026-08-17T10:00:00.000Z'}
  ];

  async function loadProjects(force=false){
    if(!force && cache.length) return cache;
    try { const r=await fetch(API,{cache:'no-store'}); const d=await r.json(); if(d.ok){cache=d.projects||[]; return cache;} } catch(e){}
    cache=[...FALLBACK]; return cache;
  }
  async function getProject(id){
    try{const r=await fetch(`${API}?id=${encodeURIComponent(id)}`,{cache:'no-store'});const d=await r.json();if(d.ok)return d.project;}catch(e){}
    return (await loadProjects()).find(p=>String(p.id)===String(id));
  }
  function escapeHtml(value=''){return String(value).replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[ch]));}
  function getImages(project){return Array.isArray(project.images)?project.images.filter(Boolean):(project.image?[project.image]:[]);}
  function projectCard(p){const images=getImages(p);const image=images[0]?`<img src="${images[0]}" alt="${escapeHtml(p.title)}" loading="lazy">`:`<div class="project-fallback"><span>${escapeHtml(p.category)}</span><strong>${escapeHtml(p.title)}</strong></div>`;return `<a class="project-card reveal project-link-card" href="project.html?id=${encodeURIComponent(p.id)}"><div class="project-thumb">${image}${images.length>1?`<span class="card-photo-count">${images.length} foto</span>`:''}</div><div class="project-label"><span>${escapeHtml(p.category)}</span><strong>${escapeHtml(p.title)}</strong></div></a>`;}
  async function renderHomeProjects(){const grid=document.getElementById('homeProjectGrid');if(!grid)return;const projects=(await loadProjects()).sort((a,b)=>new Date(b.createdAt||0)-new Date(a.createdAt||0));grid.innerHTML=projects.slice(0,4).map(projectCard).join('')||'<p class="empty-projects">Belum ada project.</p>';requestAnimationFrame(()=>grid.querySelectorAll('.reveal').forEach(el=>el.classList.add('in-view')));}
  async function initProjectListPage(){const grid=document.getElementById('allProjectsGrid');if(!grid)return;const all=await loadProjects(),filter=document.getElementById('projectCategoryFilter'),sort=document.getElementById('projectSort'),search=document.getElementById('projectSearch'),count=document.getElementById('projectCount');const categories=[...new Set(all.map(p=>p.category).filter(Boolean))].sort();filter.innerHTML='<option value="all">Semua kategori</option>'+categories.map(c=>`<option value="${escapeHtml(c)}">${escapeHtml(c)}</option>`).join('');function render(){let projects=[...cache],q=(search.value||'').trim().toLowerCase();if(filter.value!=='all')projects=projects.filter(p=>p.category===filter.value);if(q)projects=projects.filter(p=>`${p.title} ${p.category} ${p.description}`.toLowerCase().includes(q));if(sort.value==='oldest')projects.sort((a,b)=>new Date(a.createdAt||0)-new Date(b.createdAt||0));else if(sort.value==='az')projects.sort((a,b)=>a.title.localeCompare(b.title));else projects.sort((a,b)=>new Date(b.createdAt||0)-new Date(a.createdAt||0));count.textContent=`${projects.length} project${projects.length===1?'':'s'}`;grid.innerHTML=projects.map(projectCard).join('')||'<div class="empty-projects"><h3>Project tidak ditemukan</h3><p>Coba ubah kategori atau kata kunci pencarian.</p></div>';requestAnimationFrame(()=>grid.querySelectorAll('.reveal').forEach(el=>el.classList.add('in-view')));}[filter,sort,search].forEach(el=>el.addEventListener('input',render));render();}
  async function initProjectDetail(){const mount=document.getElementById('projectDetail');if(!mount)return;const id=new URLSearchParams(location.search).get('id');const project=await getProject(id);if(!project){mount.innerHTML='<div class="detail-empty"><h1>Project tidak ditemukan</h1><p>Project mungkin sudah dihapus.</p><a class="btn btn-solid-purple" href="projects.html">Kembali ke Projects</a></div>';return;}const images=getImages(project);const gallery=images.length?`<div class="project-gallery">${images.map((src,i)=>`<button class="gallery-item ${i===0?'active':''}" type="button" data-gallery-src="${src}"><img src="${src}" alt="${escapeHtml(project.title)} — foto ${i+1}" loading="lazy"><span>${i+1}</span></button>`).join('')}</div>`:'<div class="project-gallery-empty">Belum ada foto gallery.</div>';const main=images[0]?`<div class="project-main-image"><img id="mainProjectImage" src="${images[0]}" alt="${escapeHtml(project.title)}"></div>`:`<div class="detail-fallback"><span>${escapeHtml(project.category)}</span><strong>${escapeHtml(project.title)}</strong></div>`;mount.innerHTML=`<div class="project-detail-visual">${main}${gallery}</div><div class="project-detail-copy"><span class="detail-category">${escapeHtml(project.category)}</span><div class="detail-photo-total">${images.length?`${images.length} foto dalam project ini`:'Tanpa foto'}</div><h1>${escapeHtml(project.title)}</h1><p>${escapeHtml(project.description)}</p><div class="detail-actions">${project.link?`<a class="btn btn-solid-purple" href="${escapeHtml(project.link)}" target="_blank" rel="noopener">Open Project ↗</a>`:''}<a class="btn btn-lime" href="projects.html">← All Projects</a></div></div>`;const mainImg=document.getElementById('mainProjectImage');mount.querySelectorAll('[data-gallery-src]').forEach(btn=>btn.addEventListener('click',()=>{if(mainImg)mainImg.src=btn.dataset.gallerySrc;mount.querySelectorAll('.gallery-item').forEach(x=>x.classList.remove('active'));btn.classList.add('active');}));document.title=`${project.title} — Bayu Satria`;}
  window.BayuProjects={loadProjects,getProject,escapeHtml,getImages,projectCard,renderHomeProjects};
  document.addEventListener('DOMContentLoaded',()=>{renderHomeProjects();initProjectListPage();initProjectDetail();});
})();
